create table movie
(
    id           bigint generated by default as identity
        primary key,
    description  varchar(2048),
    poster_url   varchar(255),
    release_date varchar(255),
    title        varchar(512),
    version      integer
);
create table user_list
(
    id        bigserial
        primary key,
    public_id varchar(255)         not null
        unique,
    owner_id  bigint               not null
        references users,
    is_public boolean default true not null
);
create table user_list_movie
(
    id           bigserial
        primary key,
    movie_id     bigint not null
        references movie,
    rating       integer,
    view_date    date,
    user_list_id bigint not null
        references user_list,
    list_id      bigint
        constraint fk6h522al0485496n3sou7g73m
            references user_list
);
create table user_movies
(
    id        bigint generated always as identity
        primary key,
    user_id   bigint not null
        references users
            on delete cascade,
    movie_id  bigint not null
        constraint fkjy6uepbx8ri8lao8slwrkutlx
            references movie,
    view_date date,
    rating    integer
);

alter table user_movies
    owner to postgres;

create index idx_user_movies_user
    on user_movies (user_id);

create index idx_user_movies_movie
    on user_movies (movie_id);
create table users
(
    id       bigint generated always as identity
        primary key,
    username varchar(255) not null
        unique,
    password varchar(255) not null,
    email    varchar(255) not null
        unique
);

alter table users
    owner to postgres;
